apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-agent-core
  labels:
    app: agent-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-core
  template:
    metadata:
      labels:
        app: agent-core
        openebs.io/logging: "true"
    spec:
      serviceAccount: {{ .Release.Name }}-service-account
      imagePullSecrets:
        {{- include "base_pull_secrets" . }}
      initContainers:
        {{- include "base_init_core_containers" . }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: agent-core
          resources:
            limits:
              cpu: {{ .Values.core.resources.limits.cpu | quote }}
              memory: {{ .Values.core.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.core.resources.requests.cpu | quote }}
              memory: {{ .Values.core.resources.requests.memory | quote }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repo }}/mayastor-agent-core:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-s{{ .Release.Name }}-etcd:{{ .Values.etcd.service.port }}"
            - "--request-timeout={{ .Values.base.default_req_timeout }}"
            - "--cache-period={{ .Values.base.cache_poll_period }}"{{ if .Values.base.jaeger.enabled }}
            - "--jaeger={{ .Values.base.jaeger.agent.name }}:{{ .Values.base.jaeger.agent.port }}"{{ end }}
            - "--grpc-server-addr=https://0.0.0.0:50051"
          ports:
            - containerPort: 50051
          env:
            - name: RUST_LOG
              value: {{ .Values.core.logLevel }}
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
