queue_rules:
  - name: default
    merge_conditions:
      - check-success=bors-ci

pull_request_rules:
  - name: auto-label and approve backport PRs
    conditions:
      - author=mergify[bot]
      - title~=\(backport \#[0-9]+\)$
    actions:
      label:
        add:
          - kind/backport
      review:
        type: APPROVE
        message: "Automatically approved backport PR"
        bot_account: openebs-ci

  - name: merge via mergify queue
    conditions:
      - base~=^(develop|release/.*)$
      - "#approved-reviews-by>=2"
      - -label="DO NOT MERGE"
      - -label=wip
      - check-success=helm-chart-test
      - check-success=helm-images
      - check-success=submodule-branch
      - check-success=commitlint
      - check-success=DCO
    actions:
      queue:
        name: default
