name: Helm Chart CI
on:
  workflow_call:
    inputs:
      trigger:
        description: 'A run may be triggered by pull_request or merge_group'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CI: 1

jobs:
  helm-chart-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

  helm-images-pr:
    runs-on: ubuntu-latest
    if: ${{ inputs.trigger == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4

  helm-images:
    runs-on: ubuntu-latest
    if: ${{ inputs.trigger != 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      