name: Image Push
on:
  push:
    branches:
      - 'release/**'
  workflow_call:
    inputs:
      tag:
        description: 'Tag to be released (e.g. v2.9.0)'
        required: true
        type: string
      registry:
        description: 'Registry, example: ghcr.io'
        required: true
        type: string
      namespace:
        description: 'Namespace, example: mayastor/dev'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CI: 1
  TAG: ${{ inputs.tag }}

jobs:
  image-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
