name: K8s CI
on:
  workflow_call:
    inputs:
      helm-pins:
        required: false
        type: boolean
        default: false
      registry:
        required: false
        type: string
        default: ghcr.io
      namespace:
        required: false
        type: string
        default: openebs/helm-pins

jobs:
  k8s-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
  #      - name: Setup tmate session
  #        if: ${{ failure() }}
  #        timeout-minutes: 120
  #        uses: mxschmitt/action-tmate@v3
