name: Lint Commit Messages
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - staging
  merge_group:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'merge_group' && !startsWith(github.head_ref, 'mergify/merge-queue/') }}
    steps:
      - run: echo
