name: Submodule Branch Check
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - develop
      - 'release/**'
      - staging
  merge_group:

jobs:
  submodule-branch:
    runs-on: ubuntu-latest
    if: github.event_name != 'merge_group'
    steps:
      - uses: actions/checkout@v4