name: Release Helm Chart
on:
  push:
    branches:
      - develop
      - test

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Chart Changed
        id: chart_changed
        env:
          GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
          PAGER= git log -3
          if ! git diff --exit-code "origin/${GITHUB_BRANCH##*/}" ./chart; then
            echo "TRUE"
            echo "::set-output name=FLAG::true"
          else
            echo "FALSE"
            echo "::set-output name=FLAG::false"
          fi
      - name: Publish Mayastor Helm chart
        uses: stefanprodan/helm-gh-pages@v1.5.0
        if: ${{ steps.chart_changed.outputs.FLAG == 'true' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: test-pages
          charts_dir: .
