name: Release Helm Chart
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'
    branches:
      - 'release/**'

jobs:
  update-chart:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Dump vars context
        env:
          VARS_JSON: ${{ toJSON(github) }}
        run: echo "${VARS_JSON}"
      