name: Release Helm Chart
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
      - name: Pre-populate nix-shell
        run: |
          export NIX_PATH=nixpkgs=$(jq '.nixpkgs.url' nix/sources.json -r)
          echo "NIX_PATH=$NIX_PATH" >> $GITHUB_ENV
          nix-shell -p semver-tool -p yq-go --run "echo"
      - name: Publish locally in the workspace
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            tag="${{ github.ref_name }}"
            # Publish the Chart.yaml locally
            # Note this does not commit the Chart.yaml changes this the branch
            nix-shell -p semver-tool -p yq-go --run "./scripts/helm/publish-chart-yaml.sh --app-tag "$tag""
          else
            echo "Only tag pushes are supported!"
            exit 1
          fi
      - name: Publish Mayastor Helm chart
        uses: stefanprodan/helm-gh-pages@v1.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .

